### PR TITLE
Option to display QRCode even on detached projects

### PR DESCRIPTION
**Pull request by slorber**
See also https://expo.canny.io/feature-requests/p/ability-to-work-in-expo-client-after-detaching

### CODE REVIEW

**Comment by fson** [comment]
Thanks for the PR and sorry for the long response time. We don't display QR codes for detached projects, because there's no guarantee that they work with Expo Client. See https://github.com/expo/exp/pull/101#issuecomment-366592621.

**Comment by slorber** [comment]
@fson yes I know there is no guarantee, this is why I made this an option.

The idea of this option is that, if you are sure the detached project can work inside Expo client, then you use this option so that QRCode is displayed. This option would not be used most of the time.

Take a look at this first to understand: https://expo.canny.io/feature-requests/p/ability-to-work-in-expo-client-after-detaching

**Comment by terribleben** [comment]
Hi, can you help us understand your use case more?

I read your canny request, and I'm still not sure I understand the value of this workflow. By definition, apps that need to be detached pretty much always stop working in Expo Client. I realize you can do a bunch of work to guard against this by wrapping all your api calls (as you detailed in the canny request), but that sounds like it would be a ton of work for most projects, and lead to confusion for people and higher support burden for Expo. It's already fairly hard to work in ExpoKit projects (which is something we're working on improving) and I'm wary about adding even more complexity to the process unless this would be super valuable for a lot of users right away.

Since you're linking against native code and writing native code, is there something wrong with the current workflow of deploying your detached binary from Xcode instead of using Expo Client?

**Comment by slorber** [comment]
Hi

The point of this workflow is that I can be the only one using xcode to
build the real project while all others can keep working inside expo
client.

This means it's easier to onboard new team members, and they can work on
ios apps without Mac, they all have a simpler dev experience and the burden
of xcode is only on me.


I don't think it's particularly a lot of work to handle the API wrapping.
Many of us have to detach just to add a single lib like Intercom.


Yes this workflow can be confusing if you don't really understand how Expo
works. I'm not saying it should be  highlighted too much, but it would be
appreciated to ensure people can use such workflow more easily.





Le 2 mars 2018 23:20, "Ben Roth" <notifications@github.com> a écrit :

Hi, can you help us understand your use case more?

I read your canny request, and I'm still not sure I understand the value of
this workflow. By definition, apps that need to be detached pretty much
always stop working in Expo Client. I realize you can do a bunch of work to
guard against this by wrapping all your api calls (as you detailed in the
canny request), but that sounds like it would be a ton of work for most
projects, and lead to confusion for people and higher support burden for
Expo. It's already fairly hard to work in ExpoKit projects (which is
something we're working on improving) and I'm wary about adding even more
complexity to the process unless this would be super valuable for a lot of
users right away.

Since you're linking against native code and writing native code, is there
something wrong with the current workflow of deploying your detached binary
from Xcode instead of using Expo Client?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/expo/exp/pull/89#issuecomment-370069496>, or mute the
thread

**Pull request closed without merging**
