### PR TITLE
Swap chalk for turbocolor

### PR DESCRIPTION
**Pull request by jorgebucaran**
Hello @fson, @jesseruder and maintainers! 👋 

This is a PR for your consideration that swaps chalk for [turbocolor](https://github.com/jorgebucaran/turbocolor).

It ought to give you a perf boost as turbocolor loads **_>20x_** faster and applies styles **_>18x_** faster than chalk for essentially the same API. Let me know if this looks good to you and if you'd like to accept my contribution.

<pre>
# Load Time
chalk: 15.190ms
<b>turbocolor: 0.777ms</b>

# All Colors
chalk × 8,729 ops/sec
<b>turbocolor × 158,383 ops/sec</b>

# Chained Colors
chalk × 1,838 ops/sec
<b>turbocolor × 39,830 ops/sec</b>

# Nested Colors
chalk × 4,049 ops/sec
<b>turbocolor × 59,833 ops/sec</b>
</pre>

You can find more about the benchmarks [here](https://github.com/jorgebucaran/turbocolor/tree/master/bench#benchmarks). Cheers!

### CODE REVIEW

**Comment by fson** [comment]
Thanks for the PR! The benchmark looks quite convincing. However, we'd have to ensure that all the formatting stays the same after this change. There are probably quite some corner cases that chalk needs to handle, e.g. with different terminals and Windows support. Do you have any ideas how to ensure that this doesn't break anything? Right now turbocolor only has 5 test cases while chalk has over 50.

Seeing that you're the author of turbocolor (nice work!), and your library seems to be a drop in replacement for chalk, have you considered running it though the test suite of chalk? That would give us more confidence that there are no corner cases that could differ between the libraries. Before merging this PR, it would also be nice to see a couple of screenshots comparing the output before and after the change, probably from Windows too.

**Comment by jorgebucaran** [comment]
@fson That's a reasonable request. Do you have a timeline for that? I could certainly look into testing it out on Windows, but I have to admit it will take me some time. 😅

**Comment by fson** [comment]
I don't have a timeline for that, I just view having a good test coverage as prerequisite for switching, given that chalk has that and also receives more testing through being one of the most installed node libraries. There's no rush, we could look into this again when the testing situation for turbocolor improves in the future.

**Comment by fson** [comment]
Thanks for contributing to exp! exp has been replaced by Expo CLI. We welcome contributions in the new [Expo CLI repository](https://github.com/expo/expo-cli).

[Contributing to Expo CLI](https://github.com/expo/expo-cli/blob/master/CONTRIBUTING.md)

**Comment by jorgebucaran** [comment]
👋 @fson Thanks for letting me know!

**Pull request closed without merging**
